<?php
/**
 * Preview Page Configuration
 * Generates the PreviewConfig JavaScript object for preview.js
 * 
 * This file is included by preview.php to separate config from template
 */
?>
<!-- Preview Configuration (needed before preview.js) -->
<script>
window.PreviewConfig = {
    // URLs and settings
    baseUrl: <?= json_encode(rtrim(BASE_URL, '/')) ?>,
    adminUrl: <?= json_encode($router->url('')) ?>,
    managementUrl: <?= json_encode(rtrim(BASE_URL, '/') . '/management/') ?>,
    projectStyleUrl: <?= json_encode(rtrim(BASE_URL, '/') . '/style/style.css') ?>,
    authToken: <?= json_encode($router->getToken()) ?>,
    structureUrl: <?= json_encode($router->url('structure')) ?>,
    multilingual: <?= json_encode(CONFIG['MULTILINGUAL_SUPPORT'] ?? false) ?>,
    defaultLang: <?= json_encode(CONFIG['LANGUAGE_DEFAULT'] ?? 'en') ?>,
    
    // Theme mode
    themeModeEnabled: <?= json_encode(CONFIG['THEME_MODE_ENABLED'] ?? false) ?>,
    themeDefault: <?= json_encode(CONFIG['THEME_DEFAULT'] ?? 'light') ?>,
    themeUserToggle: <?= json_encode(CONFIG['THEME_USER_TOGGLE_ENABLED'] ?? false) ?>,
    
    // Translations — always-needed keys (used by preview.js core and always-active panels).
    // Panel-specific keys are in i18nPanels below and merged on first tab activation.
    i18n: {
        // ── Common ──
        delete: <?= json_encode(__admin('common.delete', 'Delete')) ?>,
        edit: <?= json_encode(__admin('common.edit', 'Edit')) ?>,
        error: <?= json_encode(__admin('common.error', 'Error')) ?>,
        loading: <?= json_encode(__admin('common.loading', 'Loading')) ?>,
        noResults: <?= json_encode(__admin('common.noResults', 'No results')) ?>,
        remove: <?= json_encode(__admin('common.remove', 'Remove')) ?>,
        save: <?= json_encode(__admin('common.save', 'Save')) ?>,
        saveFailed: <?= json_encode(__admin('common.saveFailed', 'Save failed')) ?>,
        saving: <?= json_encode(__admin('common.saving', 'Saving')) ?>,
        search: <?= json_encode(__admin('common.search', 'Search')) ?>,

        // ── Mode toolbar ──
        modeSelect: <?= json_encode(__admin('preview.modeSelect', 'Select')) ?>,
        modeDrag: <?= json_encode(__admin('preview.modeDrag', 'Drag')) ?>,
        modeStyle: <?= json_encode(__admin('preview.modeStyle', 'Style')) ?>,
        modeAdd: <?= json_encode(__admin('preview.modeAdd', 'Add')) ?>,
        modeText: <?= json_encode(__admin('preview.modeText', 'Text')) ?>,
        modeJs: <?= json_encode(__admin('preview.modeJs', 'JS')) ?>,
        miniplayer: <?= json_encode(__admin('preview.miniplayer', 'Miniplayer')) ?>,

        // ── Node / element management ──
        autoGenerated: <?= json_encode(__admin('preview.autoGenerated', 'Auto-generated')) ?>,
        confirmDeleteNode: <?= json_encode(__admin('preview.confirmDeleteNode', 'Delete this element?')) ?>,
        deleteLastTextWarning: <?= json_encode(__admin('preview.deleteLastTextWarning', "This is the last element containing text content. Deleting it will create a text-less component (styling shape only). The resulting element must have dimensions set via CSS to remain visible.\n\nContinue?")) ?>,
        editInTranslations: <?= json_encode(__admin('preview.editInTranslations', 'Edit in Translations')) ?>,
        elementAdded: <?= json_encode(__admin('preview.elementAdded', 'Element added')) ?>,
        elementUpdated: <?= json_encode(__admin('preview.elementUpdated', 'Element updated')) ?>,
        nodeDeleted: <?= json_encode(__admin('preview.nodeDeleted', 'Element deleted')) ?>,
        textNodeDeleted: <?= json_encode(__admin('preview.textNodeDeleted', 'Text node deleted')) ?>,
        confirmDeleteTextNode: <?= json_encode(__admin('preview.confirmDeleteTextNode', 'Delete this text node?')) ?>,

        // ── Text editing ──
        textContent: <?= json_encode(__admin('preview.textContent', 'Text Content')) ?>,
        textHintRaw: <?= json_encode(__admin('preview.textHintRaw', 'Enter raw text. This will be displayed as-is.')) ?>,
        textHintTranslation: <?= json_encode(__admin('preview.textHintTranslation', 'Enter a translation key. Value will be looked up in translations.')) ?>,
        textHintVariable: <?= json_encode(__admin('preview.textHintVariable', 'Enter variable name (without {{ }}). Value will be passed from parent.')) ?>,
        textModeNone: <?= json_encode(__admin('preview.textModeNone', 'None (container only)')) ?>,
        textModeRaw: <?= json_encode(__admin('preview.textModeRaw', 'Raw Text')) ?>,
        textModeTranslation: <?= json_encode(__admin('preview.textModeTranslation', 'Translation Key')) ?>,
        textModeVariable: <?= json_encode(__admin('preview.textModeVariable', 'Variable {{...}}')) ?>,
        textPlaceholderRaw: <?= json_encode(__admin('preview.textPlaceholderRaw', 'e.g. Hello World')) ?>,
        textPlaceholderTranslation: <?= json_encode(__admin('preview.textPlaceholderTranslation', 'e.g. component.myButton.label')) ?>,
        textPlaceholderVariable: <?= json_encode(__admin('preview.textPlaceholderVariable', 'e.g. buttonText')) ?>,
        textSaved: <?= json_encode(__admin('preview.textSaved', 'Text saved')) ?>,
        textKeyAutoGenerated: <?= json_encode(__admin('preview.textKeyAutoGenerated', 'Auto-generated text key')) ?>,

        // ── Component management ──
        componentAdded: <?= json_encode(__admin('preview.componentAdded', 'Component added')) ?>,
        componentUpdated: <?= json_encode(__admin('preview.componentUpdated', 'Component updated')) ?>,
        componentCreated: <?= json_encode(__admin('preview.componentCreated', 'Component created')) ?>,
        componentCreateFailed: <?= json_encode(__admin('preview.componentCreateFailed', 'Failed to create component')) ?>,
        componentNamePrompt: <?= json_encode(__admin('preview.componentNamePrompt', 'Component name (letters, numbers, hyphens):')) ?>,
        componentNameInvalid: <?= json_encode(__admin('preview.componentNameInvalid', 'Invalid name. Use only letters, numbers, hyphens, and underscores.')) ?>,
        componentNameExists: <?= json_encode(__admin('preview.componentNameExists', 'A component with this name already exists.')) ?>,
        componentNameRequired: <?= json_encode(__admin('preview.componentNameRequired', 'Component name is required')) ?>,
        componentSaved: <?= json_encode(__admin('preview.componentSaved', 'Component saved successfully!')) ?>,
        componentWarning: <?= json_encode(__admin('preview.componentWarning', 'Editing component template - changes affect all :count usage(s)')) ?>,
        deleteComponent: <?= json_encode(__admin('preview.deleteComponent', 'Delete')) ?>,
        confirmDeleteComponent: <?= json_encode(__admin('preview.confirmDeleteComponent', 'Delete component "%s"? This cannot be undone.')) ?>,
        componentDeleted: <?= json_encode(__admin('preview.componentDeleted', 'Component deleted')) ?>,
        componentDeleteFailed: <?= json_encode(__admin('preview.componentDeleteFailed', 'Failed to delete component')) ?>,
        searchComponents: <?= json_encode(__admin('preview.searchComponents', 'Search components...')) ?>,
        noComponentsFound: <?= json_encode(__admin('preview.noComponentsFound', 'No components found')) ?>,
        errorLoadingComponents: <?= json_encode(__admin('preview.errorLoadingComponents', 'Error loading components')) ?>,

        // ── Snippets ──
        selectSnippet: <?= json_encode(__admin('preview.selectSnippet', 'Please select a snippet')) ?>,
        snippetAdded: <?= json_encode(__admin('preview.snippetAdded', 'Snippet added')) ?>,
        noSnippetsFound: <?= json_encode(__admin('preview.noSnippetsFound', 'No snippets found')) ?>,
        errorLoadingSnippets: <?= json_encode(__admin('preview.errorLoadingSnippets', 'Error loading snippets')) ?>,
        allSnippets: <?= json_encode(__admin('preview.allSnippets', 'All')) ?>,
        noSnippetsInCategory: <?= json_encode(__admin('preview.noSnippetsInCategory', 'No snippets in this category')) ?>,
        noSnippetSelected: <?= json_encode(__admin('preview.noSnippetSelected', 'No snippet selected')) ?>,
        confirmDeleteSnippet: <?= json_encode(__admin('preview.confirmDeleteSnippet', 'Delete snippet "%s"? This action cannot be undone.')) ?>,
        snippetDeleted: <?= json_encode(__admin('preview.snippetDeleted', 'Snippet deleted successfully')) ?>,
        deleteSnippetFailed: <?= json_encode(__admin('preview.deleteSnippetFailed', 'Failed to delete snippet')) ?>,
        cannotDeleteCore: <?= json_encode(__admin('preview.cannotDeleteCore', 'Cannot delete core snippets')) ?>,
        snippetNameRequired: <?= json_encode(__admin('preview.snippetNameRequired', 'Snippet name is required')) ?>,
        snippetIdRequired: <?= json_encode(__admin('preview.snippetIdRequired', 'Snippet ID is required')) ?>,
        snippetIdInvalid: <?= json_encode(__admin('preview.snippetIdInvalid', 'ID must start with a letter and contain only letters, numbers, dashes')) ?>,
        snippetSaved: <?= json_encode(__admin('preview.snippetSaved', 'Snippet saved successfully!')) ?>,
        searchSnippets: <?= json_encode(__admin('preview.searchSnippets', 'Search snippets...')) ?>,

        // ── Style editor (contextual panel — always visible in style mode) ──
        addStyle: <?= json_encode(__admin('preview.addStyle', 'Add Style')) ?>,
        clickToPickColor: <?= json_encode(__admin('preview.clickToPickColor', 'Click to pick color')) ?>,
        colorValue: <?= json_encode(__admin('preview.colorValue', '#000000 or rgba(...)')) ?>,
        copyStyleFrom: <?= json_encode(__admin('preview.copyStyleFrom', 'Copy From…')) ?>,
        copyStyleFromLabel: <?= json_encode(__admin('preview.copyStyleFromLabel', 'Copy styles from:')) ?>,
        failedToLoadStyles: <?= json_encode(__admin('preview.failedToLoadStyles', 'Failed to load styles')) ?>,
        noBaseStyles: <?= json_encode(__admin('preview.noBaseStyles', 'No base styles')) ?>,
        noVariablesAvailable: <?= json_encode(__admin('preview.noVariablesAvailable', 'No variables available')) ?>,
        openTransformEditor: <?= json_encode(__admin('preview.openTransformEditor', 'Open Transform Editor')) ?>,
        propertyAdded: <?= json_encode(__admin('preview.propertyAdded', 'Property added')) ?>,
        propertyAlreadyExists: <?= json_encode(__admin('preview.propertyAlreadyExists', 'Property already exists')) ?>,
        propertyDeleted: <?= json_encode(__admin('preview.propertyDeleted', 'Property deleted')) ?>,
        searchProperties: <?= json_encode(__admin('preview.searchProperties', 'Search properties...')) ?>,
        selectProperty: <?= json_encode(__admin('preview.selectProperty', 'Select property...')) ?>,
        selectVariable: <?= json_encode(__admin('preview.selectVariable', 'Select variable')) ?>,
        state: <?= json_encode(__admin('preview.state', 'State')) ?>,
        style: <?= json_encode(__admin('preview.style', 'Style')) ?>,
        stylesReset: <?= json_encode(__admin('preview.stylesReset', 'Styles reset')) ?>,
        stylesSaved: <?= json_encode(__admin('preview.stylesSaved', 'Styles saved')) ?>,
        transformEmpty: <?= json_encode(__admin('preview.transformEmpty', 'No transform functions')) ?>,
        transformValue: <?= json_encode(__admin('preview.transformValue', 'translateX(10px) rotate(5deg)')) ?>,
        useCustomProperty: <?= json_encode(__admin('preview.useCustomProperty', 'Use custom:')) ?>,
        varReplacementWarning: <?= json_encode(__admin('preview.varReplacementWarning', 'CSS variables will be replaced with actual values')) ?>,

        // ── Transition editor (floating panel, on-demand) ──
        addPropertyFailed: <?= json_encode(__admin('preview.addPropertyFailed', 'Failed to add property')) ?>,
        animationAdded: <?= json_encode(__admin('preview.animationAdded', 'Animation added')) ?>,
        animationRemoved: <?= json_encode(__admin('preview.animationRemoved', 'Animation removed')) ?>,
        deletePropertyFailed: <?= json_encode(__admin('preview.deletePropertyFailed', 'Failed to delete property')) ?>,
        errorAddingAnimation: <?= json_encode(__admin('preview.errorAddingAnimation', 'Error adding animation')) ?>,
        errorLoadingKeyframes: <?= json_encode(__admin('preview.errorLoadingKeyframes', 'Error loading keyframes')) ?>,
        errorRemovingAnimation: <?= json_encode(__admin('preview.errorRemovingAnimation', 'Error removing animation')) ?>,
        keyframeNotFound: <?= json_encode(__admin('preview.keyframeNotFound', 'Keyframe not found')) ?>,
        keyframePropertyValue: <?= json_encode(__admin('preview.keyframePropertyValue', 'value')) ?>,
        loadTransitionFailed: <?= json_encode(__admin('preview.loadTransitionFailed', 'Failed to load transition')) ?>,
        noAnimationToPreview: <?= json_encode(__admin('preview.noAnimationToPreview', 'No animation to preview')) ?>,
        noElementsFound: <?= json_encode(__admin('preview.noElementsFound', 'No elements found')) ?>,
        noKeyframesFound: <?= json_encode(__admin('preview.noKeyframesFound', 'No keyframes found')) ?>,
        noPropertiesToTransition: <?= json_encode(__admin('preview.noPropertiesToTransition', 'No properties to transition')) ?>,
        noTriggerStyles: <?= json_encode(__admin('preview.noTriggerStyles', 'No trigger styles')) ?>,
        noTriggersWithoutTransition: <?= json_encode(__admin('preview.noTriggersWithoutTransition', 'No triggers without transition')) ?>,
        playsOn: <?= json_encode(__admin('preview.playsOn', 'plays on')) ?>,
        previewingHover: <?= json_encode(__admin('preview.previewingHover', 'Previewing hover')) ?>,
        previewNotAvailable: <?= json_encode(__admin('preview.previewNotAvailable', 'Preview not available')) ?>,
        saveTransitionFailed: <?= json_encode(__admin('preview.saveTransitionFailed', 'Failed to save transition')) ?>,
        transitionSaved: <?= json_encode(__admin('preview.transitionSaved', 'Transition saved')) ?>,

        // ── JS Interactions panel (on-demand) ──
        addInteraction: <?= json_encode(__admin('preview.addInteraction', 'Add Interaction')) ?>,
        advanced: <?= json_encode(__admin('preview.advanced', 'Advanced')) ?>,
        confirmDeleteInteraction: <?= json_encode(__admin('preview.confirmDeleteInteraction', 'Delete this interaction?')) ?>,
        containerSelector: <?= json_encode(__admin('preview.containerSelector', 'Container selector')) ?>,
        containerSelectorHint: <?= json_encode(__admin('preview.containerSelectorHint', 'Container element whose first child is the template. Each array item clones it.')) ?>,
        editInteraction: <?= json_encode(__admin('preview.editInteraction', 'Edit Interaction')) ?>,
        emptyText: <?= json_encode(__admin('preview.emptyText', 'Empty text:')) ?>,
        emptyTextPlaceholder: <?= json_encode(__admin('preview.emptyTextPlaceholder', 'e.g. No items found  (optional)')) ?>,
        emptyTextHint: <?= json_encode(__admin('preview.emptyTextHint', 'Text shown when the array is empty')) ?>,
        functionGroupCore: <?= json_encode(__admin('preview.functionGroupCore', 'Core Functions')) ?>,
        functionGroupCustom: <?= json_encode(__admin('preview.functionGroupCustom', 'Custom Functions')) ?>,
        functionGroupOther: <?= json_encode(__admin('preview.functionGroupOther', 'Other')) ?>,
        interactionAdded: <?= json_encode(__admin('preview.interactionAdded', 'Interaction added')) ?>,
        interactionDeleted: <?= json_encode(__admin('preview.interactionDeleted', 'Interaction deleted')) ?>,
        interactionUpdated: <?= json_encode(__admin('preview.interactionUpdated', 'Interaction updated')) ?>,
        interactionNotFound: <?= json_encode(__admin('preview.interactionNotFound', 'Interaction not found')) ?>,
        listModeHint: <?= json_encode(__admin('preview.listModeHint', "Uses data-bind attributes inside the container's first child as item template.")) ?>,
        newInteraction: <?= json_encode(__admin('preview.newInteraction', 'New Interaction')) ?>,
        noElementSelected: <?= json_encode(__admin('preview.noElementSelected', 'No element selected')) ?>,
        noInteractionData: <?= json_encode(__admin('preview.noInteractionData', 'No interaction data available')) ?>,
        noInteractions: <?= json_encode(__admin('preview.noInteractions', 'No interactions')) ?>,
        noParams: <?= json_encode(__admin('preview.noParams', 'No parameters')) ?>,
        removeFunction: <?= json_encode(__admin('preview.removeFunction', 'Remove function')) ?>,
        responseField: <?= json_encode(__admin('preview.responseField', 'Response field')) ?>,
        responseMapping: <?= json_encode(__admin('preview.responseMapping', 'Response Mapping')) ?>,
        responseMappingHint: <?= json_encode(__admin('preview.responseMappingHint', 'Map API response fields to page elements')) ?>,
        addMapping: <?= json_encode(__admin('preview.addMapping', 'Add Mapping')) ?>,
        noResponseSchema: <?= json_encode(__admin('preview.noResponseSchema', 'No response schema defined for this endpoint')) ?>,
        paramName: <?= json_encode(__admin('preview.paramName', 'Parameter name')) ?>,
        paramRequired: <?= json_encode(__admin('preview.paramRequired', 'Required')) ?>,
        paramValue: <?= json_encode(__admin('preview.paramValue', 'Value')) ?>,
        searchClass: <?= json_encode(__admin('preview.searchClass', 'Search class')) ?>,
        selectApi: <?= json_encode(__admin('preview.selectApi', 'Select API')) ?>,
        selectComponent: <?= json_encode(__admin('preview.selectComponent', 'Select Component')) ?>,
        selectComponentFirst: <?= json_encode(__admin('preview.selectComponentFirst', 'Select a component first')) ?>,
        selectComponentPlaceholder: <?= json_encode(__admin('preview.selectComponentPlaceholder', '-- Select component --')) ?>,
        selectEndpoint: <?= json_encode(__admin('preview.selectEndpoint', 'Select endpoint')) ?>,
        selectEvent: <?= json_encode(__admin('preview.selectEvent', 'Select event')) ?>,
        selectEventAndFunction: <?= json_encode(__admin('preview.selectEventAndFunction', 'Please select an event and function')) ?>,
        selectEventApiEndpoint: <?= json_encode(__admin('preview.selectEventApiEndpoint', 'Please select an event, API, and endpoint')) ?>,
        selectFunction: <?= json_encode(__admin('preview.selectFunction', 'Select function')) ?>,
        selectNodeFirst: <?= json_encode(__admin('preview.selectNodeFirst', 'Select an element first')) ?>,
        selectorOrThis: <?= json_encode(__admin('preview.selectorOrThis', 'selector or this')) ?>,
        targetAttribute: <?= json_encode(__admin('preview.targetAttribute', 'Attribute (optional)')) ?>,
        targetSelector: <?= json_encode(__admin('preview.targetSelector', 'Target selector')) ?>,
        thisElement: <?= json_encode(__admin('preview.thisElement', 'this element')) ?>,

        // ── Drag tool ──
        dragLock: <?= json_encode(__admin('preview.dragLock', 'Lock')) ?>,
        dragUndo: <?= json_encode(__admin('preview.dragUndo', 'Undo')) ?>,
        dragRedo: <?= json_encode(__admin('preview.dragRedo', 'Redo')) ?>,
        dragSelectHint: <?= json_encode(__admin('preview.dragSelectHint', 'Click to select, arrows to navigate, hold to drag')) ?>,
        dragLockedHint: <?= json_encode(__admin('preview.dragLockedHint', 'Element locked — drag to move, click to re-select')) ?>,
        dragToReorder: <?= json_encode(__admin('preview.dragToReorder', 'Drag to reorder')) ?>,
        elementMoved: <?= json_encode(__admin('preview.elementMoved', 'Element moved')) ?>,
        elementMoveUndone: <?= json_encode(__admin('preview.elementMoveUndone', 'Move undone')) ?>,
        elementMoveRedone: <?= json_encode(__admin('preview.elementMoveRedone', 'Move redone')) ?>,

        // ── Variables panel (component editing) ──
        variables: <?= json_encode(__admin('preview.variables', 'Variables')) ?>,
        variablesSaved: <?= json_encode(__admin('preview.variablesSaved', 'Variable saved')) ?>,
        variablesValueRequired: <?= json_encode(__admin('preview.variablesValueRequired', 'Value cannot be empty')) ?>,
        variablesNodeInfo: <?= json_encode(__admin('preview.variablesNodeInfo', 'Showing: %s')) ?>,
        variablesClickToSelect: <?= json_encode(__admin('preview.variablesClickToSelect', 'Click to select this node')) ?>,
        variablesSectionText: <?= json_encode(__admin('preview.variablesSectionText', 'Text Variables')) ?>,
        variablesSectionParams: <?= json_encode(__admin('preview.variablesSectionParams', 'Parameters')) ?>,
        variablesTypeTranslation: <?= json_encode(__admin('preview.variablesTypeTranslation', 'Translation Key')) ?>,
        variablesTypeVariable: <?= json_encode(__admin('preview.variablesTypeVariable', 'Variable {{...}}')) ?>,
        variablesTypeRaw: <?= json_encode(__admin('preview.variablesTypeRaw', 'Raw Text')) ?>,
        variablesTypeString: <?= json_encode(__admin('preview.variablesTypeString', 'Literal String')) ?>,
        variablesPlaceholderTranslation: <?= json_encode(__admin('preview.variablesPlaceholderTranslation', 'Search or type a translation key')) ?>,
        variablesCreateKey: <?= json_encode(__admin('preview.variablesCreateKey', 'Create')) ?>,
        variablesCreateKeyValue: <?= json_encode(__admin('preview.variablesCreateKeyValue', 'Value')) ?>,
        variablesKeyCreated: <?= json_encode(__admin('preview.variablesKeyCreated', 'Translation key created')) ?>,
        variablesKeyCreateError: <?= json_encode(__admin('preview.variablesKeyCreateError', 'Failed to create translation key')) ?>,
        variablesPlaceholderVariable: <?= json_encode(__admin('preview.variablesPlaceholderVariable', 'e.g. SUBTITLE')) ?>,
        variablesPlaceholderRaw: <?= json_encode(__admin('preview.variablesPlaceholderRaw', 'e.g. Raw Value')) ?>,
        variablesPlaceholderParamString: <?= json_encode(__admin('preview.variablesPlaceholderParamString', 'e.g. /page/link')) ?>,
        variablesHintVariable: <?= json_encode(__admin('preview.variablesHintVariable', '{{}} added automatically — use CAPS by convention')) ?>,
        variablesHintRaw: <?= json_encode(__admin('preview.variablesHintRaw', '__RAW__ added automatically — same in all languages')) ?>,
        variablesTypeEnum: <?= json_encode(__admin('preview.variablesTypeEnum', 'Enum')) ?>,
        variablesHintEnum: <?= json_encode(__admin('preview.variablesHintEnum', 'Resolved from enum definition at render time')) ?>,
        variablesSelectEnum: <?= json_encode(__admin('preview.variablesSelectEnum', 'Select an enum variable')) ?>,

        // ── Enums panel (component editing) ──
        enums: <?= json_encode(__admin('preview.enums', 'Enums')) ?>,
        enumSource: <?= json_encode(__admin('preview.enumSource', 'Source key')) ?>,
        enumDefault: <?= json_encode(__admin('preview.enumDefault', 'Default')) ?>,
        enumKey: <?= json_encode(__admin('preview.enumKey', 'Key')) ?>,
        enumValue: <?= json_encode(__admin('preview.enumValue', 'Value')) ?>,
        enumKeyPlaceholder: <?= json_encode(__admin('preview.enumKeyPlaceholder', 'key')) ?>,
        enumValuePlaceholder: <?= json_encode(__admin('preview.enumValuePlaceholder', 'value')) ?>,
        enumAddOption: <?= json_encode(__admin('preview.enumAddOption', 'Add Option')) ?>,
        enumSourceRequired: <?= json_encode(__admin('preview.enumSourceRequired', 'Source key is required')) ?>,
        enumNeedsOptions: <?= json_encode(__admin('preview.enumNeedsOptions', 'At least one option is required')) ?>,
        enumSaved: <?= json_encode(__admin('preview.enumSaved', 'Enum saved')) ?>,
        enumDeleted: <?= json_encode(__admin('preview.enumDeleted', 'Enum deleted')) ?>,
        enumCssStubsCreated: <?= json_encode(__admin('preview.enumCssStubsCreated', 'CSS stubs created: %s')) ?>,
        emulation: <?= json_encode(__admin('preview.emulation', 'Variable Emulation')) ?>,
        noVariablesToEmulate: <?= json_encode(__admin('preview.noVariablesToEmulate', 'No variables found in this component')) ?>,
        emulationApply: <?= json_encode(__admin('preview.emulationApply', 'Apply Preview')) ?>,
        emulationReset: <?= json_encode(__admin('preview.emulationReset', 'Reset All')) ?>,
        emulationResetField: <?= json_encode(__admin('preview.emulationResetField', 'Reset this field')) ?>,
        emulationApplied: <?= json_encode(__admin('preview.emulationApplied', 'Emulation applied')) ?>,
        enumConfirmDelete: <?= json_encode(__admin('preview.enumConfirmDelete', 'Delete enum "%s"?')) ?>,
        enumRenameTip: <?= json_encode(__admin('preview.enumRenameTip', 'Rename')) ?>,
        enumNamePlaceholder: <?= json_encode(__admin('preview.enumNamePlaceholder', 'enum_name')) ?>,
        enumNameRequired: <?= json_encode(__admin('preview.enumNameRequired', 'Enum name is required')) ?>,
        enumNameDuplicate: <?= json_encode(__admin('preview.enumNameDuplicate', 'Enum "%s" already exists')) ?>,
        enumValueType: <?= json_encode(__admin('preview.enumValueType', 'Value type')) ?>,
        enumType: <?= json_encode(__admin('preview.enumType', 'Type')) ?>,
        enumTypeDefault: <?= json_encode(__admin('preview.enumTypeDefault', '(default)')) ?>,
        enumTypeLiteral: <?= json_encode(__admin('preview.enumTypeLiteral', 'Literal')) ?>,
        enumTypeOverrideTip: <?= json_encode(__admin('preview.enumTypeOverrideTip', 'Click to override type for this row')) ?>,

        // ── Tag dropdown (add element) ──
        starTag: <?= json_encode(__admin('preview.starTag', 'Add to favorites')) ?>,
        unstarTag: <?= json_encode(__admin('preview.unstarTag', 'Remove from favorites')) ?>,
        requiresParams: <?= json_encode(__admin('preview.requiresParams', 'Requires additional parameters')) ?>,
        noPropertiesFound: <?= json_encode(__admin('preview.noPropertiesFound', 'No properties found')) ?>,
        noComponents: <?= json_encode(__admin('preview.noComponents', 'No components')) ?>
    },

    // Panel-specific i18n keys, merged into PreviewConfig.i18n on first tab activation.
    // Keys here are ONLY used by the named panel and not by preview.js core.
    // Add ensureI18nPanel(tabName) call in preview.js initStyleTabs() to activate.
    i18nPanels: {

        // ── Theme tab (preview-style-theme.js) ──
        theme: {
            noChanges: <?= json_encode(__admin('preview.noChanges', 'No changes')) ?>,
            noColorVariables: <?= json_encode(__admin('preview.noColorVariables', 'No color variables')) ?>,
            noFontVariables: <?= json_encode(__admin('preview.noFontVariables', 'No font variables')) ?>,
            noSpacingVariables: <?= json_encode(__admin('preview.noSpacingVariables', 'No spacing variables')) ?>,
            themeLoadError: <?= json_encode(__admin('preview.themeLoadError', 'Failed to load theme')) ?>,
            themeReset: <?= json_encode(__admin('preview.themeReset', 'Theme reset')) ?>,
            themeSaved: <?= json_encode(__admin('preview.themeSaved', 'Theme saved')) ?>,
            themeSaveError: <?= json_encode(__admin('preview.themeSaveError', 'Failed to save theme')) ?>,
            variableCollision: <?= json_encode(__admin('preview.variableCollision', 'Variable name collision!')) ?>,
            variableCollisionChild: <?= json_encode(__admin('preview.variableCollisionChild', 'Variable used by child component!')) ?>,
            variableCollisionChildHint: <?= json_encode(__admin('preview.variableCollisionChildHint', 'is used by:')) ?>,
            variableCollisionHint: <?= json_encode(__admin('preview.variableCollisionHint', 'These variables exist in both parent and child:')) ?>,
            variableDuplicate: <?= json_encode(__admin('preview.variableDuplicate', 'Duplicate variable!')) ?>,
            variableDuplicateHint: <?= json_encode(__admin('preview.variableDuplicateHint', 'already exists in this component.')) ?>
        },

        // ── Selectors tab (preview-style-selectors.js) ──
        selectors: {
            createSelector: <?= json_encode(__admin('preview.createSelector', 'Create')) ?>,
            noSelectorsWithRules: <?= json_encode(__admin('preview.noSelectorsWithRules', 'No other selectors with styles found')) ?>,
            noStylesToCopy: <?= json_encode(__admin('preview.noStylesToCopy', 'No styles found on source selector')) ?>,
            searchSelectors: <?= json_encode(__admin('preview.searchSelectors', 'Search selectors…')) ?>,
            selectorCreated: <?= json_encode(__admin('preview.selectorCreated', 'Selector created')) ?>,
            selectorCreateError: <?= json_encode(__admin('preview.selectorCreateError', 'Failed to create selector')) ?>,
            selectorsLoadError: <?= json_encode(__admin('preview.selectorsLoadError', 'Failed to load selectors')) ?>
        },

        // ── Animations tab (preview-style-animations.js) ──
        animations: {
            addFrame: <?= json_encode(__admin('preview.addFrame', 'Add Frame')) ?>,
            addKeyframeProperty: <?= json_encode(__admin('preview.addKeyframeProperty', 'Add Property')) ?>,
            atLeastOneFrame: <?= json_encode(__admin('preview.atLeastOneFrame', 'At least one frame required')) ?>,
            cannotDeleteLastFrame: <?= json_encode(__admin('preview.cannotDeleteLastFrame', 'Cannot delete last frame')) ?>,
            cannotDeleteLastProperty: <?= json_encode(__admin('preview.cannotDeleteLastProperty', 'Cannot delete last property')) ?>,
            confirmDeleteKeyframe: <?= json_encode(__admin('preview.confirmDeleteKeyframe', 'Delete this keyframe?')) ?>,
            createKeyframe: <?= json_encode(__admin('preview.createKeyframe', 'Create Keyframe')) ?>,
            customProperty: <?= json_encode(__admin('preview.customProperty', 'Custom Property')) ?>,
            deleteFrame: <?= json_encode(__admin('preview.deleteFrame', 'Delete Frame')) ?>,
            deleteKeyframeFailed: <?= json_encode(__admin('preview.deleteKeyframeFailed', 'Failed to delete keyframe')) ?>,
            deleteKeyframeProperty: <?= json_encode(__admin('preview.deleteKeyframeProperty', 'Delete Property')) ?>,
            dragToMoveFrame: <?= json_encode(__admin('preview.dragToMoveFrame', 'Drag to move frame')) ?>,
            editKeyframe: <?= json_encode(__admin('preview.editKeyframe', 'Edit Keyframe')) ?>,
            enterFramePercent: <?= json_encode(__admin('preview.enterFramePercent', 'Enter frame percent (0-100)')) ?>,
            enterValue: <?= json_encode(__admin('preview.enterValue', 'Enter value')) ?>,
            frame: <?= json_encode(__admin('preview.frame', 'Frame')) ?>,
            frameExists: <?= json_encode(__admin('preview.frameExists', 'Frame already exists')) ?>,
            frames: <?= json_encode(__admin('preview.frames', 'frames')) ?>,
            invalidKeyframeName: <?= json_encode(__admin('preview.invalidKeyframeName', 'Invalid keyframe name')) ?>,
            invalidPercent: <?= json_encode(__admin('preview.invalidPercent', 'Invalid percent value')) ?>,
            keyframeCreated: <?= json_encode(__admin('preview.keyframeCreated', 'Keyframe created')) ?>,
            keyframeDeleted: <?= json_encode(__admin('preview.keyframeDeleted', 'Keyframe deleted')) ?>,
            keyframeExistsConfirm: <?= json_encode(__admin('preview.keyframeExistsConfirm', 'Keyframe exists. Overwrite?')) ?>,
            keyframeNameRequired: <?= json_encode(__admin('preview.keyframeNameRequired', 'Keyframe name required')) ?>,
            keyframePropertyName: <?= json_encode(__admin('preview.keyframePropertyName', 'property')) ?>,
            keyframeSaved: <?= json_encode(__admin('preview.keyframeSaved', 'Keyframe saved')) ?>,
            loadAnimationsFailed: <?= json_encode(__admin('preview.loadAnimationsFailed', 'Failed to load animations')) ?>,
            loadKeyframeFailed: <?= json_encode(__admin('preview.loadKeyframeFailed', 'Failed to load keyframe')) ?>,
            mayBeTriggeredVia: <?= json_encode(__admin('preview.mayBeTriggeredVia', 'May be triggered via')) ?>,
            noAnimationSelectors: <?= json_encode(__admin('preview.noAnimationSelectors', 'No animated selectors')) ?>,
            noDirectTrigger: <?= json_encode(__admin('preview.noDirectTrigger', 'No direct trigger')) ?>,
            noFramesToPreview: <?= json_encode(__admin('preview.noFramesToPreview', 'No frames to preview')) ?>,
            noTransitions: <?= json_encode(__admin('preview.noTransitions', 'No transitions')) ?>,
            previewAnimation: <?= json_encode(__admin('preview.previewAnimation', 'Preview Animation')) ?>,
            previewFailed: <?= json_encode(__admin('preview.previewFailed', 'Preview failed')) ?>,
            previewingAnimation: <?= json_encode(__admin('preview.previewingAnimation', 'Previewing animation')) ?>,
            saveKeyframeFailed: <?= json_encode(__admin('preview.saveKeyframeFailed', 'Failed to save keyframe')) ?>,
            states: <?= json_encode(__admin('preview.states', 'States')) ?>,
            toggleStates: <?= json_encode(__admin('preview.toggleStates', 'Toggle States')) ?>
        }
    }
};
</script>

<!-- Preview JavaScript Modules (load order matters) -->
<script src="<?= rtrim(BASE_URL, '/') ?>/admin/assets/js/pages/preview/preview-state.js?v=<?= filemtime(PUBLIC_CONTENT_PATH . '/admin/assets/js/pages/preview/preview-state.js') ?>"></script>
<script src="<?= rtrim(BASE_URL, '/') ?>/admin/assets/js/pages/preview/preview-navigation.js?v=<?= filemtime(PUBLIC_CONTENT_PATH . '/admin/assets/js/pages/preview/preview-navigation.js') ?>"></script>
<script src="<?= rtrim(BASE_URL, '/') ?>/admin/assets/js/pages/preview/preview-style-theme.js?v=<?= filemtime(PUBLIC_CONTENT_PATH . '/admin/assets/js/pages/preview/preview-style-theme.js') ?>"></script>
<script src="<?= rtrim(BASE_URL, '/') ?>/admin/assets/js/pages/preview/preview-style-animations.js?v=<?= filemtime(PUBLIC_CONTENT_PATH . '/admin/assets/js/pages/preview/preview-style-animations.js') ?>"></script>
<script src="<?= rtrim(BASE_URL, '/') ?>/admin/assets/js/pages/preview/preview-style-selectors.js?v=<?= filemtime(PUBLIC_CONTENT_PATH . '/admin/assets/js/pages/preview/preview-style-selectors.js') ?>"></script>
<script src="<?= rtrim(BASE_URL, '/') ?>/admin/assets/js/pages/preview/preview-style-editor.js?v=<?= filemtime(PUBLIC_CONTENT_PATH . '/admin/assets/js/pages/preview/preview-style-editor.js') ?>"></script>
<script src="<?= rtrim(BASE_URL, '/') ?>/admin/assets/js/pages/preview/preview-js-interactions.js?v=<?= filemtime(PUBLIC_CONTENT_PATH . '/admin/assets/js/pages/preview/preview-js-interactions.js') ?>"></script>
<script src="<?= rtrim(BASE_URL, '/') ?>/admin/assets/js/pages/preview/preview-transition-editor.js?v=<?= filemtime(PUBLIC_CONTENT_PATH . '/admin/assets/js/pages/preview/preview-transition-editor.js') ?>"></script>
<script src="<?= rtrim(BASE_URL, '/') ?>/admin/assets/js/pages/preview/preview-miniplayer.js?v=<?= filemtime(PUBLIC_CONTENT_PATH . '/admin/assets/js/pages/preview/preview-miniplayer.js') ?>"></script>
<script src="<?= rtrim(BASE_URL, '/') ?>/admin/assets/js/pages/preview/preview-sidebar-resize.js?v=<?= filemtime(PUBLIC_CONTENT_PATH . '/admin/assets/js/pages/preview/preview-sidebar-resize.js') ?>"></script>
<script src="<?= rtrim(BASE_URL, '/') ?>/admin/assets/js/pages/preview/preview-drag.js?v=<?= filemtime(PUBLIC_CONTENT_PATH . '/admin/assets/js/pages/preview/preview-drag.js') ?>"></script>

<!-- Preview JavaScript (Main) -->
<script src="<?= rtrim(BASE_URL, '/') ?>/admin/assets/js/pages/preview/preview.js?v=<?= filemtime(PUBLIC_CONTENT_PATH . '/admin/assets/js/pages/preview/preview.js') ?>"></script>
