<?php
/**
 * Role Definitions for Permission System
 * 
 * Auto-updated: 2026-01-03 13:21:38
 */

return array (
  'viewer' => 
  array (
    'description' => 'Read-only access to structure, content, and styles',
    'builtin' => true,
    'commands' => 
    array (
      0 => 'help',
      1 => 'getSizeInfo',
      2 => 'getStructure',
      3 => 'getRoutes',
      4 => 'getSiteMap',
      5 => 'listComponents',
      6 => 'listPages',
      7 => 'getTranslation',
      8 => 'getTranslations',
      9 => 'getTranslationKeys',
      10 => 'getLangList',
      11 => 'listAssets',
      12 => 'getStyles',
      13 => 'getRootVariables',
      14 => 'listStyleRules',
      15 => 'getStyleRule',
      16 => 'getKeyframes',
      17 => 'listAliases',
      18 => 'listBuilds',
      19 => 'getBuild',
      20 => 'listRoles',
      21 => 'getMyPermissions',
    ),
  ),
  'editor' => 
  array (
    'description' => 'Edit content including structure, translations, and assets',
    'builtin' => true,
    'commands' => 
    array (
      0 => 'help',
      1 => 'getSizeInfo',
      2 => 'getStructure',
      3 => 'getRoutes',
      4 => 'getSiteMap',
      5 => 'listComponents',
      6 => 'listPages',
      7 => 'getTranslation',
      8 => 'getTranslations',
      9 => 'getTranslationKeys',
      10 => 'getLangList',
      11 => 'listAssets',
      12 => 'getStyles',
      13 => 'getRootVariables',
      14 => 'listStyleRules',
      15 => 'getStyleRule',
      16 => 'getKeyframes',
      17 => 'listAliases',
      18 => 'listBuilds',
      19 => 'getBuild',
      20 => 'listRoles',
      21 => 'getMyPermissions',
      22 => 'editStructure',
      23 => 'addRoute',
      24 => 'deleteRoute',
      25 => 'setTranslationKeys',
      26 => 'deleteTranslationKeys',
      27 => 'validateTranslations',
      28 => 'getUnusedTranslationKeys',
      29 => 'analyzeTranslations',
      30 => 'addLang',
      31 => 'deleteLang',
      32 => 'setDefaultLang',
      33 => 'setMultilingual',
      34 => 'checkStructureMulti',
      35 => 'uploadAsset',
      36 => 'deleteAsset',
      37 => 'updateAssetMeta',
      38 => 'createAlias',
      39 => 'deleteAlias',
    ),
  ),
  'designer' => 
  array (
    'description' => 'Edit styles, CSS variables, animations, and visual elements',
    'builtin' => true,
    'commands' => 
    array (
      0 => 'help',
      1 => 'getSizeInfo',
      2 => 'getStructure',
      3 => 'getRoutes',
      4 => 'getSiteMap',
      5 => 'listComponents',
      6 => 'listPages',
      7 => 'getTranslation',
      8 => 'getTranslations',
      9 => 'getTranslationKeys',
      10 => 'getLangList',
      11 => 'listAssets',
      12 => 'getStyles',
      13 => 'getRootVariables',
      14 => 'listStyleRules',
      15 => 'getStyleRule',
      16 => 'getKeyframes',
      17 => 'listAliases',
      18 => 'listBuilds',
      19 => 'getBuild',
      20 => 'listRoles',
      21 => 'getMyPermissions',
      22 => 'editStructure',
      23 => 'addRoute',
      24 => 'deleteRoute',
      25 => 'setTranslationKeys',
      26 => 'deleteTranslationKeys',
      27 => 'validateTranslations',
      28 => 'getUnusedTranslationKeys',
      29 => 'analyzeTranslations',
      30 => 'addLang',
      31 => 'deleteLang',
      32 => 'setDefaultLang',
      33 => 'setMultilingual',
      34 => 'checkStructureMulti',
      35 => 'uploadAsset',
      36 => 'deleteAsset',
      37 => 'updateAssetMeta',
      38 => 'createAlias',
      39 => 'deleteAlias',
      40 => 'editStyles',
      41 => 'setRootVariables',
      42 => 'setStyleRule',
      43 => 'deleteStyleRule',
      44 => 'setKeyframes',
      45 => 'deleteKeyframes',
      46 => 'editFavicon',
      47 => 'editTitle',
    ),
  ),
  'developer' => 
  array (
    'description' => 'Build, deploy, and download site packages',
    'builtin' => true,
    'commands' => 
    array (
      0 => 'help',
      1 => 'getSizeInfo',
      2 => 'getStructure',
      3 => 'getRoutes',
      4 => 'getSiteMap',
      5 => 'listComponents',
      6 => 'listPages',
      7 => 'getTranslation',
      8 => 'getTranslations',
      9 => 'getTranslationKeys',
      10 => 'getLangList',
      11 => 'listAssets',
      12 => 'getStyles',
      13 => 'getRootVariables',
      14 => 'listStyleRules',
      15 => 'getStyleRule',
      16 => 'getKeyframes',
      17 => 'listAliases',
      18 => 'listBuilds',
      19 => 'getBuild',
      20 => 'listRoles',
      21 => 'getMyPermissions',
      22 => 'editStructure',
      23 => 'addRoute',
      24 => 'deleteRoute',
      25 => 'setTranslationKeys',
      26 => 'deleteTranslationKeys',
      27 => 'validateTranslations',
      28 => 'getUnusedTranslationKeys',
      29 => 'analyzeTranslations',
      30 => 'addLang',
      31 => 'deleteLang',
      32 => 'setDefaultLang',
      33 => 'setMultilingual',
      34 => 'checkStructureMulti',
      35 => 'uploadAsset',
      36 => 'deleteAsset',
      37 => 'updateAssetMeta',
      38 => 'createAlias',
      39 => 'deleteAlias',
      40 => 'editStyles',
      41 => 'setRootVariables',
      42 => 'setStyleRule',
      43 => 'deleteStyleRule',
      44 => 'setKeyframes',
      45 => 'deleteKeyframes',
      46 => 'editFavicon',
      47 => 'editTitle',
      48 => 'build',
      49 => 'deleteBuild',
      50 => 'cleanBuilds',
      51 => 'deployBuild',
      52 => 'downloadBuild',
    ),
  ),
  'admin' => 
  array (
    'description' => 'Full administrative access (except token management)',
    'builtin' => true,
    'commands' => 
    array (
      0 => 'help',
      1 => 'getSizeInfo',
      2 => 'getStructure',
      3 => 'getRoutes',
      4 => 'getSiteMap',
      5 => 'listComponents',
      6 => 'listPages',
      7 => 'getTranslation',
      8 => 'getTranslations',
      9 => 'getTranslationKeys',
      10 => 'getLangList',
      11 => 'listAssets',
      12 => 'getStyles',
      13 => 'getRootVariables',
      14 => 'listStyleRules',
      15 => 'getStyleRule',
      16 => 'getKeyframes',
      17 => 'listAliases',
      18 => 'listBuilds',
      19 => 'getBuild',
      20 => 'listRoles',
      21 => 'getMyPermissions',
      22 => 'editStructure',
      23 => 'addRoute',
      24 => 'deleteRoute',
      25 => 'setTranslationKeys',
      26 => 'deleteTranslationKeys',
      27 => 'validateTranslations',
      28 => 'getUnusedTranslationKeys',
      29 => 'analyzeTranslations',
      30 => 'addLang',
      31 => 'deleteLang',
      32 => 'setDefaultLang',
      33 => 'setMultilingual',
      34 => 'checkStructureMulti',
      35 => 'uploadAsset',
      36 => 'deleteAsset',
      37 => 'updateAssetMeta',
      38 => 'createAlias',
      39 => 'deleteAlias',
      40 => 'editStyles',
      41 => 'setRootVariables',
      42 => 'setStyleRule',
      43 => 'deleteStyleRule',
      44 => 'setKeyframes',
      45 => 'deleteKeyframes',
      46 => 'editFavicon',
      47 => 'editTitle',
      48 => 'build',
      49 => 'deleteBuild',
      50 => 'cleanBuilds',
      51 => 'deployBuild',
      52 => 'downloadBuild',
      53 => 'setPublicSpace',
      54 => 'renameSecureFolder',
      55 => 'renamePublicFolder',
      56 => 'listProjects',
      57 => 'getActiveProject',
      58 => 'switchProject',
      59 => 'createProject',
      60 => 'deleteProject',
      61 => 'backupProject',
      62 => 'listBackups',
      63 => 'restoreBackup',
      64 => 'deleteBackup',
      65 => 'exportProject',
      66 => 'importProject',
      67 => 'downloadExport',
      68 => 'clearExports',
      69 => 'getCommandHistory',
      70 => 'clearCommandHistory',
    ),
  ),
);
