<?php
/**
 * Route helpers — shared utilities for parameterised routes (beta.8 A1).
 *
 * Param routes use ':name' segments (e.g., 'products/:slug') in
 * routes.php for readability AND to match the doc's URL pattern syntax.
 * NTFS reserves ':' in path components, so any place that maps a route
 * path to a filesystem path must sanitise ':' segments to '__name'.
 *
 * **This file is the canonical source of that sanitisation.** Anywhere
 * that builds a filesystem path from a route path should:
 *   require_once __DIR__ . '/../functions/routeHelpers.php';  // adjust relative path
 *   $fsPath = paramRoutePathToFs($routePath);
 *
 * Avoids drift across inline copies (we already shipped two before
 * consolidating — see public/index.php and the bug-fix path in
 * JsonToHtmlRenderer::renderPage).
 *
 * Locked design 2026-06-04, BETA8_PARAMETERISED_ROUTES.md.
 */

if (!function_exists('paramRoutePathToFs')) {
    /**
     * Translate a route path with `:name` param segments into a
     * filesystem-safe form by replacing each `:name` with `__name`.
     *
     * Routes.php key stays ':slug' (matches doc URL syntax); page
     * folders on disk use '__slug'. Pattern matches ':' only at the
     * START of a segment (after start-of-string or '/') so that any
     * stray ':' elsewhere in a path is preserved untouched.
     *
     * Examples:
     *   'products'           → 'products'
     *   'products/:slug'     → 'products/__slug'
     *   ':lang/products'     → '__lang/products'
     *   'users/:id/profile'  → 'users/__id/profile'
     *
     * @param string $routePath
     * @return string
     */
    function paramRoutePathToFs(string $routePath): string {
        return preg_replace('#(^|/):([a-zA-Z_][a-zA-Z0-9_]*)#', '$1__$2', $routePath);
    }
}

if (!function_exists('paramRouteSegmentToFs')) {
    /**
     * Translate a single route segment from ':name' to '__name'.
     * Pass-through for segments that don't start with ':'. Useful when
     * iterating segments individually (e.g., the dispatcher's
     * resolveTemplateFile builds the path from an array of segments).
     *
     * @param string $segment
     * @return string
     */
    function paramRouteSegmentToFs(string $segment): string {
        return (strlen($segment) > 1 && $segment[0] === ':')
            ? '__' . substr($segment, 1)
            : $segment;
    }
}

if (!function_exists('compileRoutesMetaToJs')) {
    /**
     * Compile the routes structure to a JS file content string
     * exposing window.QS_ROUTES.
     *
     * Beta.8 A1 Build Slice 1. Output shape:
     *   window.QS_ROUTES = [
     *     { path: 'home',         params: [] },
     *     { path: 'test',         params: [] },
     *     { path: 'test/:slug',   params: [{ name: 'slug', type: 'string' }] },
     *     ...
     *   ];
     *
     * Why an array (not an object): order matters. qs.js's client-side
     * path matcher (Build Slice 2) walks this list and applies the
     * locked specificity rule (more literal segments wins; ties broken
     * by declaration order in routes.php). An array preserves the
     * declaration order; an object keyed by path would have to ship a
     * separate order field.
     *
     * Type default is 'string' for all params today — no admin UI to
     * declare a specific type yet (filed as a beta.9 polish in the doc).
     *
     * @param array $routes The ROUTES constant value (nested associative)
     * @return string JS file content
     */
    function compileRoutesMetaToJs(array $routes): string {
        $flat = _flattenRoutesForMeta($routes);

        $jsArray = [];
        foreach ($flat as $r) {
            $jsArray[] = ['path' => $r['path'], 'params' => $r['params']];
        }

        $json = json_encode($jsArray, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

        $js  = "/**\n";
        $js .= " * QuickSite Routes Schema (qs-route-schema.js)\n";
        $js .= " * Auto-generated by addRoute/deleteRoute/build — DO NOT EDIT\n";
        $js .= " * Generated: " . date('Y-m-d H:i:s') . "\n";
        $js .= " *\n";
        $js .= " * Consumed by qs.js's client-side path matcher (beta.8 A1) —\n";
        $js .= " * walks this array on page load, matches location.pathname\n";
        $js .= " * against each pattern, and exposes captured values via\n";
        $js .= " * QS.routeParams.<name>. Specificity rule + declaration\n";
        $js .= " * order determine which wins; the array order here is the\n";
        $js .= " * declaration order so the matcher iterates as authored.\n";
        $js .= " */\n";
        $js .= "window.QS_ROUTES = " . $json . ";\n";

        return $js;
    }
}

if (!function_exists('_flattenRoutesForMeta')) {
    /**
     * Recursively flatten the nested routes structure into a list of
     * records {path, params}. Walks every node (parent routes are
     * themselves routable in QuickSite). Helper for compileRoutesMetaToJs.
     *
     * @param array  $routes Nested routes (from ROUTES constant)
     * @param string $prefix Accumulated path prefix (recursion state)
     * @return array<int, array{path:string, params:array}>
     */
    function _flattenRoutesForMeta(array $routes, string $prefix = ''): array {
        $result = [];
        foreach ($routes as $key => $children) {
            // Allow integer keys to coexist (shouldn't happen in valid
            // routes.php but defensive — cast to string).
            $key = (string) $key;
            $path = $prefix === '' ? $key : $prefix . '/' . $key;

            // Extract :name segments as params. Default type is 'string';
            // type-aware route schema is a beta.9 enhancement.
            $params = [];
            foreach (explode('/', $path) as $segment) {
                if (strlen($segment) > 1 && $segment[0] === ':') {
                    $params[] = ['name' => substr($segment, 1), 'type' => 'string'];
                }
            }

            $result[] = ['path' => $path, 'params' => $params];

            if (is_array($children) && !empty($children)) {
                foreach (_flattenRoutesForMeta($children, $path) as $nested) {
                    $result[] = $nested;
                }
            }
        }
        return $result;
    }
}

if (!function_exists('writeRoutesMetaFile')) {
    /**
     * Compile + write the routes schema to a target file path.
     * Used by addRoute / deleteRoute (PUBLIC_CONTENT_PATH/scripts/...) +
     * build.php (build-output/scripts/...) to keep the file fresh
     * wherever it lives.
     *
     * @param array  $routes     Routes structure (post-mutation)
     * @param string $targetPath Absolute path for the JS file
     * @return bool True on success
     */
    function writeRoutesMetaFile(array $routes, string $targetPath): bool {
        $dir = dirname($targetPath);
        if (!is_dir($dir)) {
            if (!@mkdir($dir, 0755, true) && !is_dir($dir)) {
                return false;
            }
        }
        $js = compileRoutesMetaToJs($routes);
        return file_put_contents($targetPath, $js, LOCK_EX) !== false;
    }
}

if (!function_exists('fsRoutePathToParam')) {
    /**
     * Reverse of paramRoutePathToFs — translate `__name` filesystem
     * segments back to `:name` route-pattern syntax. Used when SCANNING
     * the filesystem (e.g., scanAllPageJsonFiles) to derive route
     * identities from on-disk paths.
     *
     * Without this, admin UIs / API responses would surface 'test/__slug'
     * instead of 'test/:slug' — confusing because the user authored the
     * route as ':slug' in routes.php.
     *
     * Pattern matches `__` only at the start of a segment (after start
     * or '/'), so existing folders named like 'foo__bar' stay untouched.
     *
     * Examples:
     *   'products'           → 'products'
     *   'products/__slug'    → 'products/:slug'
     *   '__lang/products'    → ':lang/products'
     *
     * @param string $fsRoutePath
     * @return string
     */
    function fsRoutePathToParam(string $fsRoutePath): string {
        return preg_replace('#(^|/)__([a-zA-Z][a-zA-Z0-9_]*)#', '$1:$2', $fsRoutePath);
    }
}

if (!function_exists('substituteRouteParams')) {
    /**
     * Substitute every `{:name}` placeholder in `$str` with the matching
     * value from `$routeParams`. Missing params resolve to '' (matches
     * the prior inline behaviour in the OAuth dispatcher).
     *
     * Used by side-effect resolver kinds (oauth-start, oauth-callback,
     * future oauth-logout, …) to resolve `{:routeParam}` references in
     * resolver config fields (provider, callback_url, …) against the
     * URL's captured params before the handler is invoked.
     *
     * Examples (routeParams = ['provider' => 'google']):
     *   '{:provider}'                         → 'google'
     *   '/auth/oauth/{:provider}/callback'    → '/auth/oauth/google/callback'
     *   'no-placeholders-here'                → 'no-placeholders-here'
     *   '{:missing}'                          → ''
     *
     * Locked design 2026-06-14, DESIGN_DECISIONS.md "OAuth handleStart shape".
     *
     * @param string                $str
     * @param array<string, string> $routeParams
     * @return string
     */
    function substituteRouteParams(string $str, array $routeParams): string {
        return preg_replace_callback(
            '/\{:(\w+)\}/',
            function ($m) use ($routeParams) {
                return isset($routeParams[$m[1]]) ? (string) $routeParams[$m[1]] : '';
            },
            $str
        );
    }
}
